# Schema for the configuration files of the disable_login module.

disable_login.settings:
  type: config_object
  label: 'Disable Login settings'
  mapping:
    disable_login:
      type: boolean
      label: 'Disable Login'
    querystring:
      type: string
      label: 'Querystring'
    secret:
      type: string
      label: 'Secret Key'
